name: Go

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24.4'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Install Linux dependencies  
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc pkg-config libgl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev libasound2-dev

    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        xcode-select --version || xcode-select --install || true

    - name: Download dependencies
      run: |
        go mod download
        go mod verify

    - name: Format code
      run: go fmt ./...

    - name: Build TUI
      env:
        CGO_ENABLED: 0
      run: go build -v ./...

    - name: Build GUI
      env:
        CGO_ENABLED: 1
      run: go build -tags gui -v ./... || echo "GUI build failed, continuing"

    - name: Test
      env:
        CGO_ENABLED: 1
      run: go test -v ./...

    - name: Test with race detector
      env:
        CGO_ENABLED: 1
      run: go test -race -v ./...

    - name: Vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests with coverage (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage report
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
        retention-days: 30