name: Create Pre-Release

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write

jobs:
  pre-release:
    # Only run if the PR was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all commits and tags
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'
    
    - name: Get last pre-release tag or create new one
      id: last-pre-release-tag
      run: |
        # Fetch all tags
        git fetch --tags

        # Fetch only the tags that match the pre-release format
        pre_release_tags=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*-rc*' --sort=-v:refname)

        # Get the last pre-release tag
        last_pre_release_tag=$(echo "$pre_release_tags" | head -n 1)

        if [ -z "$last_pre_release_tag" ]; then
          # If no pre-release tags found, get the last release tag
          last_release_tag=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n 1)
          if [ -z "$last_release_tag" ]; then
            # If no release tags found, start with v0.1.0-rc.1
            new_pre_release_tag="v0.1.0-rc.1"
          else
            # Extract version parts and create first RC
            version_without_v=${last_release_tag#v}
            IFS='.' read -r major minor patch <<< "$version_without_v"
            new_pre_release_tag="v$major.$minor.$patch-rc.1"
          fi
          echo "No pre-release tags found. Creating a new one: $new_pre_release_tag"
        else
          echo "Last pre-release tag: $last_pre_release_tag"
          # Extract RC number and increment (standardize to -rc.X format)
          if [[ "$last_pre_release_tag" == *"-rc."* ]]; then
            # Already in -rc.X format
            version_part=${last_pre_release_tag%-rc.*}
            rc_part=${last_pre_release_tag##*-rc.}
          else
            # Convert from -rcX to -rc.X format
            version_part=${last_pre_release_tag%-rc*}
            rc_part=${last_pre_release_tag##*-rc}
          fi
          incremented_rc_number=$((rc_part + 1))
          new_pre_release_tag="$version_part-rc.$incremented_rc_number"
        fi

        echo "new_pre_release_tag=$new_pre_release_tag" >> $GITHUB_OUTPUT
        echo "New pre-release tag: $new_pre_release_tag"

    - name: Build binaries
      run: |
        # Create build directory
        mkdir -p build
        
        # Extract version for filename
        VERSION=${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}
        
        # Build for different platforms with version in filename
        echo "Building for Linux (amd64)..."
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-linux-amd64 .
        
        echo "Building for Linux (arm64)..."
        GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-linux-arm64 .
        
        echo "Building for Windows (amd64)..."
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-windows-amd64.exe .
        
        echo "Building for Windows (arm64)..."
        GOOS=windows GOARCH=arm64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-windows-arm64.exe .
        
        echo "Building for macOS (amd64)..."
        GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-macos-amd64 .
        
        echo "Building for macOS (arm64)..."
        GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.version=$VERSION" -o build/tala-$VERSION-macos-arm64 .

    - name: Create checksums
      run: |
        cd build
        sha256sum * > checksums.txt
        echo "Checksums created:"
        cat checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}
        name: Pre-release ${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}
        body: |
          ## Pre-release ${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}
          
          This is a pre-release version created from PR #${{ github.event.pull_request.number }}.
          
          ### Changes
          ${{ github.event.pull_request.title }}
          
          ### Downloads
          - **Linux**: `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-linux-amd64`, `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-linux-arm64`
          - **Windows**: `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-windows-amd64.exe`, `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-windows-arm64.exe`
          - **macOS**: `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-macos-amd64`, `tala-${{ steps.last-pre-release-tag.outputs.new_pre_release_tag }}-macos-arm64`
          
          ### Installation
          1. Download the appropriate binary for your platform
          2. Make it executable (Linux/macOS): `chmod +x tala-*`
          3. Run: `./tala-*` (or `tala-*.exe` on Windows)
          
          **Note**: This is a pre-release version and may contain bugs. Use for testing purposes only.
        files: |
          build/tala-*-linux-amd64
          build/tala-*-linux-arm64
          build/tala-*-windows-amd64.exe
          build/tala-*-windows-arm64.exe
          build/tala-*-macos-amd64
          build/tala-*-macos-arm64
          build/checksums.txt
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

